services:
  web:
    build:
      context: .
    expose:
      - 8000 # Solo esta expuesto internamente (no se publicar치 en el host)
    env_file:
      - ./.env
    volumes:
      - static-data:/app/staticfiles  # Archivos est치ticos
      - media-data:/app/media    # Archivos media
  
  # Actua como proxy inverso (gunicorn manejar치 las solicitudes y archivos est치ticos)
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static-data:/app/staticfiles  
      - media-data:/app/media         

volumes:
  static-data:
  media-data:       